$raiz = "C:\Users\Dell G3 Gaming\Documents\Default Project"
$h = (Invoke-WebRequest "https://empleosperuhoy.blogspot.com/p/empleos.html" -UseBasicParsing).Content
$h = $h -replace 'window\.location\.replace\(''/p/inicio.html''\);', '/*test: neutralizado*/'

$head = "<script>`nwindow.__errores=[];`nwindow.addEventListener('error',function(e){ window.__errores.push(String(e.message||e)); });`n</script>`n"
$h = $h.Replace("<head>", "<head>" + $head)

$gadget = "<script>`n(function(){`n  document.addEventListener('click', function(ev){`n    var t = ev.target;`n    if(!t || !t.closest) return;`n    var fl = t.closest('.flecha');`n    if(!fl) return;`n    var grupo = t.closest('.filtro-grupo');`n    if(!grupo || !grupo.classList.contains('tiene-seleccion')) return;`n    ev.preventDefault();`n    ev.stopPropagation();`n    var primero = null;`n    var cbs = grupo.querySelectorAll('input[type=`"checkbox`"]');`n    for(var i=0;i<cbs.length;i++){ cbs[i].checked = false; if(!primero) primero = cbs[i]; }`n    var abiertos = document.querySelectorAll('.filtro-grupo.abierto');`n    for(var j=0;j<abiertos.length;j++){ abiertos[j].classList.remove('abierto'); }`n    if(primero){ primero.dispatchEvent(new Event('change', {bubbles:true})); }`n  }, true);`n})();`n</script>`n"

$driver = "<script>`nwindow.addEventListener('load', function(){ setTimeout(pasarTest, 4000); });`nfunction fin(res){`n  res.errores = (window.__errores||[]).slice(0,5);`n  var s = 'TESTX:' + JSON.stringify(res);`n  document.title = s;`n  var d = document.createElement('div'); d.id='TESTX'; d.textContent = s;`n  document.body.appendChild(d);`n}`nfunction pasarTest(){`n  try{`n    var res = {ok:false};`n    res.portal = !!document.querySelector('.portal-empleos');`n    res.navport = !!document.querySelector('.portal-navport');`n    res.gruposTotal = document.querySelectorAll('.filtro-grupo').length;`n    res.conData = document.querySelectorAll('.filtro-grupo[data-filtro]').length;`n    res.conCheckbox = document.querySelectorAll('.filtro-grupo input[type=checkbox]').length;`n    res.pathname = location.pathname;`n    var gs = document.querySelectorAll('.filtro-grupo[data-filtro]');`n    var g = null;`n    for(var i=0;i<gs.length;i++){ if(gs[i].querySelector('input[type=`"checkbox`"]')){ g=gs[i]; break; } }`n    if(!g){ return fin(res); }`n    var cb = g.querySelector('input[type=`"checkbox`"]');`n    res.grupo = g.getAttribute('data-filtro');`n    cb.checked = true;`n    cb.dispatchEvent(new Event('change',{bubbles:true}));`n    setTimeout(function(){`n      res.seleccion = g.classList.contains('tiene-seleccion');`n      var fl = g.querySelector('.flecha');`n      if(!fl){ res.err='sin flecha'; return fin(res); }`n      fl.dispatchEvent(new MouseEvent('click',{bubbles:true,cancelable:true}));`n      setTimeout(function(){`n        var limpio = true;`n        var cbs = g.querySelectorAll('input[type=checkbox]');`n        for(var k=0;k<cbs.length;k++){ if(cbs[k].checked) limpio=false; }`n        res.checksLimpios = limpio;`n        res.sinAbierto = !g.classList.contains('abierto');`n        res.ok = res.seleccion && limpio && res.sinAbierto;`n        fin(res);`n      }, 1500);`n    }, 1500);`n  }catch(e){ fin({ok:false, err:String(e)}); }`n}`n</script>`n"

$out = $h.Replace("</body>", $gadget + $driver + "</body>")
if ($out.Length -eq $h.Length) { $out = $h + $gadget + $driver }
$tmp = Join-Path $raiz "reporte\test-x-gadget.html"
[IO.File]::WriteAllText($tmp, $out, (New-Object Text.UTF8Encoding($false)))
Write-Output ("listo: " + $out.Length)
